// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASvRJ1dSV8in0UclcgtVSDuQaUXTnMdJE',
    appId: '1:720969679338:web:46b2eddac1b40ede8df293',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    authDomain: 'agricultural-platform-db3df.firebaseapp.com',
    databaseURL: 'https://agricultural-platform-db3df-default-rtdb.firebaseio.com',
    storageBucket: 'agricultural-platform-db3df.firebasestorage.app',
    measurementId: 'G-F02XLGCRBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs5G-nX9ZFKNYe3oe0H61gzKUeIWMh6y8',
    appId: '1:720969679338:android:d513360859537ad48df293',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    databaseURL: 'https://agricultural-platform-db3df-default-rtdb.firebaseio.com',
    storageBucket: 'agricultural-platform-db3df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfv9sQv3eRcU3b9fg_G1DWr7_DCQPu9mE',
    appId: '1:720969679338:ios:1b57228d4f9b86928df293',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    databaseURL: 'https://agricultural-platform-db3df-default-rtdb.firebaseio.com',
    storageBucket: 'agricultural-platform-db3df.firebasestorage.app',
    iosClientId: '720969679338-u48d05k2l36d6ad1n6k9pfnvb9vmkfjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriculturalPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfv9sQv3eRcU3b9fg_G1DWr7_DCQPu9mE',
    appId: '1:720969679338:ios:1b57228d4f9b86928df293',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    databaseURL: 'https://agricultural-platform-db3df-default-rtdb.firebaseio.com',
    storageBucket: 'agricultural-platform-db3df.firebasestorage.app',
    iosClientId: '720969679338-u48d05k2l36d6ad1n6k9pfnvb9vmkfjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriculturalPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASvRJ1dSV8in0UclcgtVSDuQaUXTnMdJE',
    appId: '1:720969679338:web:ca6f32edee178a5d8df293',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    authDomain: 'agricultural-platform-db3df.firebaseapp.com',
    databaseURL: 'https://agricultural-platform-db3df-default-rtdb.firebaseio.com',
    storageBucket: 'agricultural-platform-db3df.firebasestorage.app',
    measurementId: 'G-EXZT8HFQF6',
  );
}
