// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:720969679338:web:YOUR_APP_ID',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    authDomain: 'agricultural-platform-db3df.firebaseapp.com',
    storageBucket: 'agricultural-platform-db3df.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:720969679338:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    storageBucket: 'agricultural-platform-db3df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:720969679338:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    storageBucket: 'agricultural-platform-db3df.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.agriculturalPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:720969679338:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    storageBucket: 'agricultural-platform-db3df.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.example.agriculturalPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:720969679338:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '720969679338',
    projectId: 'agricultural-platform-db3df',
    authDomain: 'agricultural-platform-db3df.firebaseapp.com',
    storageBucket: 'agricultural-platform-db3df.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
